### PR TITLE
[Fix]`jsx-indent`: don't check literals not within JSX

### LINKED ISSUE #2563: 7.18.2 regression: react/jsx-indent lots of false positives
Since the last version 7.18.2, eslinting [cockpit](https://github.com/cockpit-project/cockpit/) gets tons of false positives like these:
```
/var/home/martin/upstream/cockpit/pkg/systemd/init.js
  1326:20  error  Expected indentation of 12 space characters but found 0  react/jsx-indent
  1327:23  error  Expected indentation of 12 space characters but found 0  react/jsx-indent
  1327:23  error  Expected indentation of 12 space characters but found 0  react/jsx-indent
  1328:21  error  Expected indentation of 12 space characters but found 0  react/jsx-indent
  1329:23  error  Expected indentation of 12 space characters but found 0  react/jsx-indent
```

on this code, which seems perfectly well indented:
```
    function create_timer_file() {
        var unit = "[Unit]\nDescription=";
        var service = "\n[Service]\nExecStart=";
        var timer = "\n[Timer]\n";
        var install = "[Install]\nWantedBy=timers.target\n";
        var service_file = unit + timer_unit.Description + service + timer_unit.Command + "\n";
```
The dozens of other errors are also wrong. Things were fine until 7.18.0, I haven't tested 7.18.1 yet.

### PR DESCRIPTION
**Pull request by toshi-toma**
Fixes #2563

### CODE REVIEW

**Comment by toshi-toma** [comment]
Anyway, I created PR.
I'll under investigation for other cases.

**Comment by toshi-toma** [comment]
I corresponded to `JSXFragment`. 72fd950

**Comment by toshi-toma** [comment]
I think it's fixed. Please review.🙏

**Comment by ljharb** [comment]
Thanks for the fast fix!

**Pull request merged**
