### PR TITLE
[Fix] react/prefer-read-only-props fails if using Flow's $ReadOnly<T>

### PR DESCRIPTION
**Pull request by karolina-benitez**

### CODE REVIEW

**Comment by ljharb** [comment]
@karolina-benitez why close/delete?

**Comment by karolina-benitez** [comment]
I was second guessing my understanding of the issue. Just to clarify, I need to adjust the rule to allow the object level annotation `$ReadOnly` to replace the need to add the individual annotation `+` to each attribute?

**Comment by ljharb** [comment]
To be honest I'm not super clear, I'm not familiar with Flow :-/ my personal approach here would be to write the tests first, and then blunder through the implementation until i'd figured out how to fix it.

**Comment by karolina-benitez** [comment]
Gotcha, from the Flow documentation:
``` 
props: $ReadOnly<{|
    dataTest?: string,
    className?: string,
  |}>,
``` is valid syntax but the current rule is returning an error because it's expecting each individual attribute to be annotated. Like so:
``` 
props: $ReadOnly<{|
    +dataTest?: string,
    +className?: string,
  |}>,
```
I think my initial understanding was correct and the first example should pass. I'll be adjusting my tests and will reopen the PR shortly

**Comment by ljharb** [comment]
That seems right to me!

**Comment by ljharb** [comment]
@karolina-benitez would you mind restoring the branch and reopening this PR, so i can keep it in sync with #2772?

**Comment by ljharb** [comment]
To be specific, the desired workflow was to click the "restore branch" button on this PR, and then "reopen pull request". Pushing to the branch directly makes this PR unrecoverable.

**Comment by karolina-benitez** [comment]
Oh no, my mistake. What should be my next steps?

**Comment by ljharb** [comment]
If this PR in fact is unrecoverable (if there's no "restore branch" button) then I think at this point we'll just leave the other two PRs open; i'll keep them in sync, and this one will have to be left as-is.

**Comment by karolina-benitez** [comment]
Yes it is unrecoverable, I don’t see a “restore branch” button. I appreciate your patience while I stumble around, I’m still trying to figure this all out

**Comment by ljharb** [comment]
No worries, it happens.

Feel free to hit me up on any medium in the future if you want to pair on this sort of thing :-)

**Comment by karolina-benitez** [comment]
That would be incredibly helpful, thank you!

**Pull request closed without merging**
