### PR TITLE
Use full schema object instead of an array for jsx-curly-spacing

### PR DESCRIPTION
**Pull request by jseminck**
See: https://github.com/yannickcr/eslint-plugin-react/issues/1290

### CODE REVIEW

**Comment by ljharb** [comment]
@yannickcr it'd be great to release this as a semver-patch ASAP (assuming nothing minor or major is already in master)

**Comment by ZebraFlesh** [comment]
Is there something which is blocking publishing a release with this PR? Not having it is blocking upgrades from eslint 4.1.1 to 4.2.0.

**Comment by ljharb** [comment]
@ZebraFlesh in fact this PR is not necessary for upgrading to eslint 4.2.0; the v4.2.0 upgrade is necessary to avoid an error. This PR enforces the schema - without this PR, invalid configs pass.

**Comment by lukeapage** [comment]
@ljharb is it that 4.2 doesn't bail with an error but still logs an error message? That's what I experience and why I've decided to wait for this to be published before upgrading.

**Comment by ljharb** [comment]
@lukeapage yes, exactly - it logs an error message (which is easily ignored) but no longer fails. You're welcome to wait, but it's not really "blocking", it's just slightly inconvenient :-)

**Comment by ZebraFlesh** [comment]
That's exactly what I'm talking about: I don't want to try and explain to everyone why there are new errors in the logs and why they're okay.

**Comment by flamerohr** [comment]
error messages shouldn't be considered "ok" or "can be ignored", that's what *warning* messages are for
it would be good to get a resolution for this, rather than have these warnings show up

**Comment by ljharb** [comment]
This is a warning message (from eslint 4), not an error message.

**Comment by ahmadnassri** [comment]
can we please get a ping on this thread, when the next release goes out with this fix?

**Comment by msikma** [comment]
If, like me, you're annoyed by the error message, my recommendation would just be to replace your old file with [the patched one](https://raw.githubusercontent.com/jseminck/eslint-plugin-react/75fb917c1ce27540f48cbe3fa7436a6822d4b953/lib/rules/jsx-curly-spacing.js) manually for now.

Quick way to do it (from your project directory):

    curl -o ./node_modules/eslint-plugin-react/lib/rules/jsx-curly-spacing.js "https://raw.githubusercontent.com/jseminck/eslint-plugin-react/75fb917c1ce27540f48cbe3fa7436a6822d4b953/lib/rules/jsx-curly-spacing.js"

The new release will come around soon enough, assuming you don't clear out your modules too often this will clear up your terminal a bit until the next version rolls around. 🙂

**Comment by antoinerousseau** [comment]
Please publish this on NPM asap.

**Comment by yannickcr** [comment]
Released in v7.2.0, really sorry for the delay.

**Comment by Kerumen** [comment]
@yannickcr Thank you!

**Comment by Gabri3l** [comment]
Thank you for the release!!

**Pull request merged**
