### PR TITLE
[Fix] move error messages to meta property

### LINKED ISSUE #2915: Rule messages not defined in meta properties
Is there a reason some rule messages aren't defined through the meta properties, or is this just a small oversight? For example, `jsx-indent` and `jsx-indent-props` have their messages defined in the `create` function.

Is there any interest in converting these to use the meta message property to make writing tests easier in the future?

### PR DESCRIPTION
**Pull request by acdvs**
This moves all error messages for every rule to the built-in `meta.messages` property to support easier rule writing in the future.

Resolves #2915

### CODE REVIEW

**Comment by ljharb** [comment]
I’ve fixed the test failures on master and rebase this; the current failures are due to this PR.

**Comment by acdvs** [comment]
@ljharb Took a few extra commits to fix the test cases that weren't caught with local unit tests. Should be good to go after the rebase issue.

**Comment by acdvs** [comment]
@ljharb Could you provide some insight as to why the automatic rebase action is failing here? The logs say there's some conflicts but I'm not actually seeing anything.

**Comment by ljharb** [comment]
I don't see a conflict, and I'm not sure, but don't worry about it - i can merge through that if needed.

**Comment by ljharb** [comment]
Somehow it's finding 487 merge commits, and there's zero, so that's clearly a bug in the action :-)

**Comment by ljharb** [comment]
I've rebased it manually, which should resolve the issue.

**Comment by ljharb** [comment]
Turns out this further broke eslint < v4.15, since v4.15 added `messageId` support, but we weren't testing on eslint 3 so we didn't catch it. #2562 will restore support for it.

**Pull request merged**
