### PR TITLE
Add no-set-state rule

### PR DESCRIPTION
**Pull request by markdalgleish**
As explained in the updated docs in this commit: "When using an architecture that separates your application state from your UI components (e.g. Flux), it may be desirable to forbid the use of local component state."

It's highly likely that this rule might need some changes, particularly since I haven't worked with ESLint internals before, but I wanted to get my first attempt in a pull request to at least get the conversation started.

Is this a rule that you'd consider including?

### CODE REVIEW

**Comment by MoOx** [comment]
:+1:

**Comment by yannickcr** [comment]
While not covering all cases listed in #195, the rule looks fine to me. I think it is a very good start.

Do you plan to handle more cases, or can I merge it as is and we'll improve it gradually ?

**Comment by markdalgleish** [comment]
:+1: I think merging it in and improving it gradually is a good idea. I'd be keen to make this more comprehensive.

**Comment by yannickcr** [comment]
Merged, thanks!

**Comment by moroshko** [comment]
@yannickcr When can we expect to see this on npm?

**Comment by yannickcr** [comment]
@moroshko I plan to release a new version by the end of the day tomorrow.

**Comment by moroshko** [comment]
@yannickcr Thanks! Looking forward to it.

**Comment by Daniel15** [comment]
A good variant of this rule would be to only allow `setState` from "container" components (ie. components with a "Container" suffix). The pattern we follow in my team is that UI components have no state and take everything via props, and container components wrap the UI components and connect them to stores. The container components only use state, no props. In this case we'd only want the "no setState" rule to apply to UI components, not container components.

**Pull request merged**
