### PR TITLE
[New] `jsx-newline` support prevent option

### PR DESCRIPTION
**Pull request by jsphstls**
Closes: #2793

### CODE REVIEW

**Comment by lukasgjetting** [comment]
Awesome!

Maybe the rule config should use the terms `"always"` and `"never"` instead of `prevent` (like [`semi`](https://eslint.org/docs/rules/semi))?

Not sure though, as that might limit future configuration without introducing breaking changes.

**Comment by lukasgjetting** [comment]
Duplicate of #2927?

**Comment by jsphstls** [comment]
I can rename the options. I did use an object to make it easier to extend. What do you think @ljharb ?

**Comment by sladyn98** [comment]
This is great ! Thanks for solving it I was actually finding it quite difficult to find my way around it. I can understand and learn :tada:

**Review by ljharb — APPROVED** [review]

**Pull request merged**
