### PR TITLE
[New] support eslint v7

### PR DESCRIPTION
**Pull request by ljharb**

### CODE REVIEW

**Comment by toshi-toma** [comment]
@ljharb 
Would you mind if I fix tests and `node.start`?

**Comment by ljharb** [comment]
@toshi-toma i restored the test you'd removed; we shouldn't need to remove tests to get this shipped.

That test is the one failing CI, legitimately.

**Comment by toshi-toma** [comment]
@ljharb 

Oh. I understand.

I made a mistake that added the test into valid.
https://github.com/yannickcr/eslint-plugin-react/pull/2635/files#diff-f8e412f530183ea4c0e4bbfd3c3f2b0eR576-R587

We should remove the test from valid. then, should pass the failing test.

**Comment by toshi-toma** [comment]
There is an issue -> #1673

**Comment by ljharb** [comment]
ah, thanks, i understand - the test was incorrectly in "invalid" (#1673 would fix that and make it properly invalid), but the parse error in the test was making it be silently ignored.

**Pull request merged**
