### PR TITLE
Added tests for jsx-curly-spacing that deal with comments in children.

### PR DESCRIPTION
**Pull request by s-h-a-d-o-w**
See also:
https://github.com/yannickcr/eslint-plugin-react/issues/648#issuecomment-327519650

### CODE REVIEW

**Comment by oyeanuj** [comment]
@ljharb Does this seem good to merge? I'm also running into this problem.

**Comment by ljharb** [comment]
I've rebased this, and one test is still failing.

**Comment by ljharb** [comment]
Notably, the one failing test is just about failing to remove a space from before a `}`; no comments are removed.

**Comment by s-h-a-d-o-w** [comment]
Sweet, looks like this is good to go (see my commit message for details about what the problem was).

**Pull request merged**
