### PR TITLE
Chore: fix linting errors (no-trailing-spaces).

### PR DESCRIPTION
**Pull request by Aladdin-ADD**

### CODE REVIEW

**Comment by ljharb** [comment]
Does a lint rule need to be enabled?

**Comment by Aladdin-ADD** [comment]
`no-trailing-spaces`? seems it has been enabled, don't know why these code were merged. (o|o)

**Comment by ljharb** [comment]
The master build was passing before; odd.

**Comment by Aladdin-ADD** [comment]
I see. I was using a test-flight eslint, which has a update: Don’t ignore comments (no-trailing-spaces)  (#9416)

**Pull request merged**
