### PR TITLE
Fix TypeError for undefined node in PropType.shape

### PR DESCRIPTION
**Pull request by mrichmond**
#1471 checking to see if node is truthy to prevent TypeError on undefined node.

### CODE REVIEW

**Comment by richardgorman** [comment]
Hi, can we please push this change along? @mrichmond

**Comment by thomasrehm-shopgate** [comment]
Hi, when is this PR going to be merged?

**Comment by ljharb** [comment]
Regression test added.

**Comment by richardgorman** [comment]
Thanks @ljharb, can you tell me a date of when this will be released?

**Comment by ljharb** [comment]
Nope, i can’t. Only @yannickcr can do releases.

**Pull request merged**
