### PR TITLE
Case insensitive comparisons for no-target-blank

### PR DESCRIPTION
**Pull request by dmnd**
`<a href="foo" target="_BLANK">` should also trigger no-target-blank.
Now it does.

### CODE REVIEW

**Comment by ljharb** [comment]
Do browsers natively treat them as case-insensitive (and does react normalize the case)? If not, they should *not* be targeted by this rule.

**Comment by dmnd** [comment]
Looks like I was overzealous with the HTML attribute name. Those seem to be case sensitive. But target="_BLANK" definitely works: http://codepen.io/dmnd/pen/LRPmZE?editors=1010

**Comment by dmnd** [comment]
Amended to not include all-caps html attributes.

**Comment by yannickcr** [comment]
Thanks. Can you rebase your branch ? Then I think we'll be good to go.

**Comment by dmnd** [comment]
Rebased.

**Comment by yannickcr** [comment]
Perfect, thanks!

**Pull request merged**
