### PR TITLE
Add test to ensure all rules are exported

### PR DESCRIPTION
**Pull request by glenjamin**
As discussed in the comments from #5

### CODE REVIEW

**Comment by yannickcr** [comment]
Thanks.

Can you fix the coding style issues? Then we can definitely merge it.

**Comment by glenjamin** [comment]
Whoops, must have had my editor integration off! Will fix this up.

**Comment by glenjamin** [comment]
That should be updated now, got caught out by that typo that used to be in master!

**Comment by yannickcr** [comment]
Thanks again.

(And sorry for the typo)

**Pull request merged**
