### PR TITLE
Check index is not negative.

### PR DESCRIPTION
**Pull request by mattyod**

### CODE REVIEW

**Comment by yannickcr** [comment]
Hi, do you have a use case for this fix ?

**Comment by mattyod** [comment]
I was getting an error thrown as i was -1. To be honest I didn't dig much deeper as this got my lint system working on .jsx files with an npm command:

```
"lint": "eslint . --ext .jsx,.js"
```

**Comment by yannickcr** [comment]
Ok, I found that the following pattern trigger the bug:
```jsx
class Hello extends React.Component {
  static get propTypes() {} // <- empty body for the propTypes declaration
  render() {
    return <div>Hello World</div>;
  }
}
```
I'll add a this pattern to the test suite.

Thanks for the bugfix!

**Comment by mattyod** [comment]
Thanks for the quick resolution.

**Pull request merged**
