### PR TITLE
Chore: Add tests for prop-types destructuring

### PR DESCRIPTION
**Pull request by sstern6**
Fixes and verifies: https://github.com/yannickcr/eslint-plugin-react/issues/1422

### CODE REVIEW

**Comment by MatthewHerbst** [comment]
@sstern6 Would it be possible to add a deep-destructuring example as well? For example:

```javascript
class MyComponent extends React.PureComponent {
  propTypes = {
    foo: PropTypes.shape({
      // TODO: fill this out
    }).isRequired,
  }

  render() {
    return <div>{this.props.foo.bar}</div>;
  }
}
```

Expected error would be: `\'bar\' is missing in props validation'`

I ask for this because I've seen cases where sometimes destructuring works on the outer layer but not when you go deeper.

**Comment by MatthewHerbst** [comment]
@sstern6 #1422 actually reports the problem noted above, which is why I was hoping to see a deep-destructuring test in the test suite that purportedly tested it heh. Seems #1422 still isn't fixed though. I think the tests you have above are good to add regardless, but I don't think they should be said to fully fix and/or verify #1422

**Comment by sstern6** [comment]
Youre right sorry about that, ill get on a fix for the deep destructuring, got caught up in the spread operator examples.

**Comment by MatthewHerbst** [comment]
Amazing, thank you! If there's any way I can help, please let me know. I've taken a glance at it before and didn't really know where to start, but happy to look again.

**Comment by MatthewHerbst** [comment]
Wow. The robots liked this being merged!

**Pull request merged**
