### PR TITLE
Alternative Rule for `jsx-curly-spacing`

### PR DESCRIPTION
**Pull request by casesandberg**
Fixes https://github.com/yannickcr/eslint-plugin-react/issues/388 and https://github.com/yannickcr/eslint-plugin-react/issues/211

### CODE REVIEW

**Comment by yannickcr** [comment]
Merged, thanks!

**Comment by ljharb** [comment]
'Alternative' seems like a really bad option name - it's not descriptive at all, and it precludes other alternatives. @yannickcr, before releasing this, can we improve the option name?

**Comment by yannickcr** [comment]
@ljharb yes, I'm open to any suggestion.

**Comment by ljharb** [comment]
PR incoming.

**Comment by ljharb** [comment]
PR: https://github.com/yannickcr/eslint-plugin-react/pull/623

**Pull request merged**
