### PR TITLE
Transform variables

### PR DESCRIPTION
**Pull request by dfilipidisz**
Continue work on #1240.

Transformed ```var``` statements to ```const``` and ```let```, added eslint rules to enforce them.

Not included:
* Examples in docs not updated
* Test code blocks not updated

If there is anything I can do to make these large scale changes easier to handle, please let me know!

### CODE REVIEW

**Comment by ljharb** [comment]
Was this done manually, or solely with `eslint --fix`?

**Comment by dfilipidisz** [comment]
First I ran ```eslint ---fix``` than I fixed the ~15 cases where it couldn't do it by itself.

**Comment by dfilipidisz** [comment]
Okay, I'll definitely do that in the future! Thanks for guiding me along this, I don't have much experience in open source :)

**Comment by lencioni** [comment]
> I don't have much experience in open source :)

You are doing a great job! Keep it up 💃

**Pull request merged**
