### PR TITLE
[Rebased] `jsx-max-depth`: validate a specific depth for JSX

### PR DESCRIPTION
**Pull request by forabi**
Originally proposed by @chriswong (https://github.com/yannickcr/eslint-plugin-react/pull/1260)

### CODE REVIEW

**Comment by ljharb** [comment]
Please do not open duplicate PRs; collabs are able to rebase branches on behalf of the author.

**Comment by ljharb** [comment]
Separately, it's not a rebase if there's a single merge commit in it.

**Comment by ljharb** [comment]
I've replaced your branch with a proper rebase of #1260.

**Comment by forabi** [comment]
Should this be closed?

**Comment by ljharb** [comment]
I'm intentionally leaving it open so that if any changes are needed to #1260, they can be simultaneously pushed here - this minimizes the permanent pollution in the git graph by combining the two PR refs to the same sha.

It will be automatically closed when the other is merged.

**Comment by wholesomedev** [comment]
Awesome, thanks @ljharb!

**Pull request merged**
