### PR TITLE
add forbid-prop-types rule that by default forbids "any", "array", and "object"

### PR DESCRIPTION
**Pull request by pwmckenna**

### CODE REVIEW

**Comment by pwmckenna** [comment]
@jimbolla made a new branch/pr (all the naming changed)
this pr addresses https://github.com/yannickcr/eslint-plugin-react/issues/215

**Comment by yannickcr** [comment]
Looks great! Can you add some documentation ?

Also, does it handle nested propTypes ?
```jsx
class Foo extends React.Component {
    render: function () {
        return <div>{this.props.bar.baz.something}</div>
    }
}
Foo.propTypes = {
    bar: React.PropTypes.shape({               // ok
        baz: React.PropTypes.object.isRequired // not ok, PropTypes.object is forbidden
    })
};
```

**Comment by pwmckenna** [comment]
@yannickcr just added a test that verifies support for nested props. I'll get started on some documentation now. I'll flatten these commits once the docs are looking good.

**Comment by pwmckenna** [comment]
documentation added!

**Comment by yannickcr** [comment]
:+1: 

If it is good for you, can you squash your commits ? Then I will merge the PR.

**Comment by pwmckenna** [comment]
updated the docs to mention the suggested replacements, then squashed. should be good to merge once checks pass.

**Comment by yannickcr** [comment]
Merged, thanks !

**Comment by mydearxym** [comment]
this ` forbid-prop-types` seems not work in this situation:

```js
class Foo extends React.Component {
    const bar = this.props.bar;

    render: function () {
        return <div>{bar.baz.something}</div>
    }
}
Foo.propTypes = {
    bar: React.PropTypes.shape({               // ok
        baz: React.PropTypes.object.isRequired // not ok, PropTypes.object is forbidden
    })
};
```

**Comment by ljharb** [comment]
That's correct behavior - you should use a shape, or objectOf, on `baz`.

**Comment by mydearxym** [comment]
@ljharb   sorry for not make my self clear

```js
class Foo extends React.Component {
    const bar = this.props.bar;

    render: function () {
        return <div>{bar.baz}</div>
    }
}
Foo.propTypes = {
    bar: React.PropTypes.shape({  
        baz: React.PropTypes.string      // not ok, Prop defined but not used
    })
};
```

this is ok:
```js
class Foo extends React.Component {
    render: function () {
        return <div>{this.props.bar.baz}</div>
    }
}
Foo.propTypes = {
    bar: React.PropTypes.shape({  
        baz: React.PropTypes.string      // ok
    })
};
```

**Comment by ljharb** [comment]
Gotcha, can you file a new issue for that?

**Comment by mydearxym** [comment]
yes, i open #847

**Pull request merged**
