### PR TITLE
Improved multiline prop support for jsx-closing-bracket-location

### PR DESCRIPTION
**Pull request by tuures**
Currently situation where last prop is both multiline and starts at the same line as the opening bracket is not handled very well.

Example of the issue can be found here: https://github.com/yannickcr/eslint-plugin-react/issues/454#issuecomment-193284260

### CODE REVIEW

**Comment by yannickcr** [comment]
Thanks. I will review it this week, but I need to do a bit of cleanup in all "indent-related" issues first :|

**Comment by lixiaoyan** [comment]
any update on this?

**Comment by yannickcr** [comment]
Not yet, sorry. I still have a lot of triage to do in the issues first.

**Comment by tuures** [comment]
Anything that would help to close this PR? :)

**Comment by yannickcr** [comment]
(Finally) merged, thanks!

**Pull request merged**
