### PR TITLE
[Fix] `prop-types`, `propTypes`: handle React.* TypeScript types

### LINKED ISSUE #3035: [feature request] jsx-no-constructed-context-values but for all props
It will be very helpful to prevent non-stable values for **all** kinds of props to prevent mistakes that can cause needless re-renders. 

For example, to prevent such things:
```
<MySuperHeavyComponent options={{ foo: 'bar'}} />
```

### LINKED ISSUE #3045: [Bug] Enable Plugin to Properly Acknowledge Props Provided Via `React.FC`
Carryover from #2353, intended to remove the noise from the problem.

As stated in the opening comment of the original issue, this plugin does not properly validate props when `React.FC` is used. Information was provided at typescript-eslint/typescript-eslint#3075 on how to address this issue. The suggested approach just needs to be implemented.

cc: @ljharb 

## Original Opening Comment from @dchebakov 
**Tell us about your environment**

- ESLint Version: v6.0.1
- Node Version: v10.16.0
- npm Version: v6.9.0

**Configuration**

```js
module.exports = {
  parser: '@typescript-eslint/parser',
  parserOptions: {
    project: './tsconfig.json',
  },
  plugins: ['@typescript-eslint'],
  extends: [
    'plugin:react/recommended',
    'plugin:@typescript-eslint/recommended',
  ],
}
```

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```tsx
import * as React from 'react';
interface PersonProps {
    username: string;
}
const Person: React.FunctionComponent<PersonProps> = (props): React.ReactElement => (
    <div>{props.username}</div>
);
```

```bash
npx eslint src --ext .tsx
```

**What did you expect to happen?**
`eslint` show no errors, because type definition actually present in generic type `React.FunctionComponent<PersonProps>`

**What actually happened? Please include the actual, raw output from ESLint.**

```js
error    'username' is missing in props validation       react/prop-types
```

### PR DESCRIPTION
**Pull request by vedadeepta**
Fixes #3045 and related issues.

Implements logic discussed in this comment: https://github.com/yannickcr/eslint-plugin-react/issues/2777#issuecomment-683944481

### CODE REVIEW

**Comment by vedadeepta** [comment]
hmm seems like some tests are failing cause `Array.includes` isn't supported in old envs?

**Review by ljharb — APPROVED** [review]
Thanks, looks great

**Comment by vedadeepta** [comment]
> Does this solve #2777 as well?

Nope, it will show an error for code like this
```
interface Props {
    posts: string[];
}
const Home: NextPage<Props> = ({ posts }) => {
  return <span>jsx</span>
}
```

because `NextPage` is not in our `allowedGenericTypes` and this [line 945](https://github.com/yannickcr/eslint-plugin-react/blob/d74a7d82d92ba984f7bcbf62d7ebe9272b3d5154/lib/util/propTypes.js#L945) will block the construction of `declaredPropTypes` from TS interface definition.

If we want this case to be handled we need to make `allowedGenericTypes` configurable by the user.

**Comment by ljharb** [comment]
ok - we can look into that in a followup. it'd be great to allow all generic types and actually respect what they declare.

**Pull request merged**
