### PR TITLE
Rename some JSX-specific rules to include jsx- prefix

### LINKED ISSUE #668: Rename some JSX-specific rules to include "jsx-" prefix
It seems that this naming convention hasn't been applied consistently. I think that it might be helpful to rename a few rules that are JSX-specific and not really React-specific:

- no-comment-textnodes -> jsx-no-comment-textnodes
- require-extension -> jsx-require-extension
- wrap-multilines -> jsx-wrap-multilines

and maybe

- self-closing-comp -> jsx-self-closing-comp

### PR DESCRIPTION
**Pull request by lencioni**
Fixes #668, addresses #686.

### CODE REVIEW

**Comment by lencioni** [comment]
Rebased and conflicts resolved!

**Comment by ljharb** [comment]
LGTM

**Comment by yannickcr** [comment]
Merges, thanks!

**Comment by ljharb** [comment]
Finished the cleanup of this rule in 2f7a462. Since it was never released in a non-alpha, non-rc build, there's no need to keep the old one around in any form.

**Pull request merged**
