### PR TITLE
[Fix] Never call Object prototype builtins directly

### LINKED ISSUE #955: jsx-tag-spacing crashes if options object isn't passed
This simple configuration makes `jsx-tag-spacing` crash:
```
'react/jsx-tag-spacing': 1
```

A quick fix is:
```
'react/jsx-tag-spacing': [1, {}]
```

Error:
```
TypeError: Error while loading rule 'react/jsx-tag-spacing': Cannot read property 'hasOwnProperty' of undefined
    at Object.create ([...]/node_modules/eslint-plugin-react/lib/rules/jsx-tag-spacing.js:208:60)
```

### PR DESCRIPTION
**Pull request by ljharb**
Fixes #955.

I'll worry about removing all the for..in loops (which should also never be used) in a future PR.

### CODE REVIEW

**Comment by yannickcr** [comment]
This PR go way beyond fixing #955, I'd prefer to stay with a simple fix like #956 for now.

**Comment by ljharb** [comment]
We can certainly add that simple fix, but this is a systemic problem by the bad practice of calling `.hasOwnProperty` directly - which this PR nips in the bud. Is this not a change you want to make?

**Comment by yannickcr** [comment]
Well, I am not against rethinking some rules (for `hasOwnProperty` or `for...in` like you mentioned) but the use of `hasOwnProperty` here is not the reason of the problem here (the problem was the direct use of `context.options[0]` without checking it's existence before).

Also I don't like the idea to add some additional dependencies to the plugin for such things.

So for now I'd prefer to simply fix #955 then discuss about the other changes in another PR/Issue :)

**Comment by ljharb** [comment]
OK - now that #956 is merged, let's discuss it :-)

I do agree that (as I discovered when adding a test for it, which #956 did not do) that `hasOwnProperty` wasn't the problem here.

However, I'm not sure why adding an additional dependency is a problem; it's transparent to users, and this is a dev tool, not a production tool. Using prototype builtins directly is a huge footgun, and having `has` available, combined with the lint rule, ensures that developers won't run into it.

**Comment by ljharb** [comment]
@yannickcr any update on making this change?

**Comment by ljharb** [comment]
This is now updated - I'm hoping to merge it soon, please review.

**Comment by yannickcr** [comment]
Ok for me 👍

**Pull request merged**
