### PR TITLE
[Docs] Re-sort all rules alphabetically

### PR DESCRIPTION
**Pull request by ybiquitous**
To make it easier to find rules.

It will be appreciated if you review it. 😊

### CODE REVIEW

**Comment by ybiquitous** [comment]
Thanks for your review!

> is there any way we could add a CI check that prevents these from being mis-sorted?

I think it is easiest to use regular expressions, so what do you think?

For example:

```js
const pattern = /# List of supported rules([\s\S]+?)#/;
const source = '<README.md contents...>';
const ruleListText = source.match(pattern)[1];
const ruleList = ruleListText.trim().split('*');
// check sorting...
```

(I think using the markdown parser is too heavy for this task...)

**Comment by ljharb** [comment]
I'm not sure using an X parser is ever too heavy a task to parse X :-)

**Comment by ljharb** [comment]
An alternative would be to make an `npm run-script` that *generates* this list automatically, and then the CI check would simply be "run the check, and fail if there's a diff".

**Comment by ybiquitous** [comment]
Sorry for late reply 🙏 

> An alternative would be to make an npm run-script that generates this list automatically, and then the CI check would simply be "run the check, and fail if there's a diff".

Thanks, I will try it!
But diffs in this PR becomes too large, so can I do this with another PR?

**Comment by ljharb** [comment]
@ybiquitous i'm not concerned with a large diff since it can be in a different commit; is it OK if we do it in this PR?

**Comment by ybiquitous** [comment]
> is it OK if we do it in this PR?

Yes! No problem! 🙏

**Comment by ybiquitous** [comment]
This is so old. I close.

**Comment by ljharb** [comment]
That’s unfortunate; old is irrelevant. If you restore the branch and reopen the PR, and add the requested CI check, this can land.

**Comment by ybiquitous** [comment]
@ljharb Thanks for your comment. I retried via PR #2541.

**Comment by ljharb** [comment]
There's no "restore branch" button?

**Comment by ybiquitous** [comment]
I know the restore button, but I thought the branch name `readme-resort-rules` of this PR does not express the new PR #2541.
So, I opened as another PR.

Sorry for confusing you... 🙇

**Comment by ljharb** [comment]
I'd still prefer to consolidate PR refs - the branch name doesn't stick around but the PR ref does - so it'd be great if you could reopen this, and I'll be happy to manually keep this one in sync with your new one.

**Comment by ybiquitous** [comment]
OK, I will sync both. 👍

**Comment by ybiquitous** [comment]
I've cherry-picked from #2541.

**Comment by ybiquitous** [comment]
@ljharb Thanks for your suggestion. [markdown-magic](https://github.com/DavidWells/markdown-magic) can reduce the script and works very well! 

If we would publish and share the transform script, it might be better to publish as a [markdown-magic plugin](https://github.com/DavidWells/markdown-magic#adding-custom-transforms).

See also https://github.com/yannickcr/eslint-plugin-react/pull/2541#discussion_r365995925

**Comment by ybiquitous** [comment]
@ljharb Could you please review this again?

**Pull request merged**
