### PR TITLE
Fix ignorePureComponents when using class expressions.

### PR DESCRIPTION
**Pull request by dreid**
This allows the use of a React.PureComponent when used in an expression context for `prefer-stateless-function` with `ignorePureComponents`.

Example:

```js
const Foo = class extends React.PureComponent {
  render() {
    return <div>{this.props.foo}</div>;
  }
};
```

### CODE REVIEW

**Comment by ljharb** [comment]
Should this only apply when the [react version setting](https://github.com/yannickcr/eslint-plugin-react#configuration) is >= v15.3?

**Comment by ljharb** [comment]
(also, why use an expression in that example and not `class Foo extends …`?

**Comment by dreid** [comment]
> (also, why use an expression in that example and not class Foo extends …?

It's just a minimal obviously correct syntax where ignorePureComponents doesn't work right.

This also fixes usages of non-decorator wrapper functions (and maybe `export default class extends…`?) 

In practice this example probably shouldn't be allowed but that should probably be enforced by a more general eslint rule. :)

**Comment by dreid** [comment]
I'm not sure about the react version setting.

**Comment by ljharb** [comment]
I'm not super concerned about people on v15.0, 15.1, or 15.2, but someone on v0.14 shouldn't get a pass from using PureComponent.

**Comment by dreid** [comment]
Sorry, I might be misunderstanding you, are you proposing that ignorePureComponents shouldn't do anything on < 0.15.3? There do not appear to be (but maybe I missed them) any existing version constraints on ignorePureComponents.

If so, should that be done in this PR? It seems like it's a larger change that would require more discussion.

**Comment by dreid** [comment]
Is there anything else I need to do for this? I noticed there were some conflicts so I resolved them.

This was approved almost a month ago and hasn't been merged so I just wanted to make sure this wasn't waiting on some action from me.

**Comment by yannickcr** [comment]
Thanks for your work! And sorry for the delay :)

**Pull request merged**
