### PR TITLE
Target blank dynamic link should fail

### PR DESCRIPTION
**Pull request by kenearley**
Made from the suggestion in @ksdmitrieva's [issue](https://github.com/yannickcr/eslint-plugin-react/issues/1737), I believe this is the right approach even though you would get false positives since it cannot check for relative paths in dynamic links. However, I think that would be rare since it's not best practice to use `target='_blank'` on internal links anyway.

### CODE REVIEW

**Comment by ljharb** [comment]
I think that since it can generate false positives, it should be behind an option.

**Comment by kenearley** [comment]
Makes sense to me. I’ll update the pull request.

**Comment by kenearley** [comment]
@ljharb I've added the option and set "always" as the default since it seems the safer state.

One thing I noticed is that you still would not get the error if you assigned the href using spread operator to assign props. Should that be covered in another option?

**Comment by ljharb** [comment]
I think if you can expand the error so it applies to an inline spread-"href", that would be generally useful?

**Comment by ljharb** [comment]
Yes, that's generally true - but spreading props is an antipattern anyways, so it also might be OK to allow the checks to be bypassed in that case.

**Comment by ksdmitrieva** [comment]
Thanks, @kenearley, for moving this along. The whole idea of the vulnerability is when untrusted link is added without "rel=noopener". When the link is hard-coded, it's most likely trusted. Otherwise, why would you add untrusted links to your application. Untrusted links will most likely come from user input. Anyway, I'm glad this is added.
Interesting edge case with the spread operator. If it's an antipattern, I wonder if there is a rule that highlights that usage.

**Pull request merged**
