### PR TITLE
Fixes an Edge Case in jsx-pascal-case

### PR DESCRIPTION
**Pull request by dthielman**
A fun-size PR to support single letter component names. Since it's technically valid PascalCase, it shouldn't break (potential usecase: providing a wrapper component for the react tag elements).

### CODE REVIEW

**Comment by nkbt** [comment]
Fixes #505

Can we get it in please?

**Comment by ljharb** [comment]
@yannickcr this is blocking us enabling the rule in eslint-config-airbnb - it'd be great to get this in :-)

**Comment by yannickcr** [comment]
Sorry for the delay. I will try to check this today.

**Comment by yannickcr** [comment]
Merged, thanks!

**Pull request merged**
