### PR TITLE
Partial rewrite of the destructuring rule

### PR DESCRIPTION
**Pull request by HenriBeck**
Pull Request for #1709 

This introduces an object as an option for specifying different behavior for different component types.

I also added a check if we are in a `render` method for class components (don't know if this is wanted but the docs only showed examples with `render` methods).

What is still missing:
- [x] Checking for destructuring props inside the functional component body
- [x] Update tests
- [x] Update Docs
- [ ] Add an option for allowing the props inside class properties (Future PR)
- [ ] Add an option for also validating class methods (Future PR)

This also fixes a few bugs:

Fixes when the `props` aren't named `props`:
```js
function Baz(properties) {
  return (<div>{properties.children}</div>); // Didn' report here before
}
```

### CODE REVIEW

**Comment by HenriBeck** [comment]
@ljharb could you take a look?

**Comment by ljharb** [comment]
@HenriBeck i know it's been awhile; but did you have to delete the fork? This still seems useful, and I'd prefer not to have to have a different PR.

**Comment by HenriBeck** [comment]
@ljharb yeah, I just cleaned up my forks and forgot that I still had a PR open here.
I can recreate it when I have time, you can still see the changes so it shouldn't be too big of an effort.

**Comment by HenriBeck** [comment]
I also have the changes on my laptop.

**Pull request closed without merging**
