### PR TITLE
[Fix] `prop-types`: fix crash on multiple destructuring

### LINKED ISSUE #2319: Error: VariableDeclarator ASTNodes are not handled by markPropTypesAsUsed
ESLint started crashing with this error shortly after I upgraded to 7.14.0.

I suspect it's related to prop destructuring. I tried opening different JSX files and ESLint didn't seem to have a problem except for files with components that destructure their props.

Full error log: 

```
[Error - 8:04:55 PM] ESLint stack trace:
[Error - 8:04:55 PM] Error: VariableDeclarator ASTNodes are not handled by markPropTypesAsUsed
Occurred while linting /Users/.../src/pages/tournament/status.jsx:8
    at markPropTypesAsUsed (/Users/.../node_modules/eslint-plugin-react/lib/util/usedPropTypes.js:338:15)
    at Object.VariableDeclarator (/Users/.../node_modules/eslint-plugin-react/lib/util/usedPropTypes.js:492:9)
    at updatedRuleInstructions.(anonymous function) (/Users/.../node_modules/eslint-plugin-react/lib/util/Components.js:780:47)
    at listeners.(anonymous function).forEach.listener (/Users/.../node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/.../node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/.../node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/.../node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/.../node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/.../node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)
```

### PR DESCRIPTION
**Pull request by golopot**
fixes #2319

### CODE REVIEW

**Comment by dsifford** [comment]
Just confirming that this fix resolves the issue for me. :+1:

**Comment by yoyo837** [comment]
same issue with v7.14.0
```jsx
const {
  data: { declareCurrentNode },
} = this.props;
const { nodeAuditType } = declareCurrentNode;
```

**Comment by golopot** [comment]
@yoyo837 That case is covered by this pr.

**Comment by yoyo837** [comment]
But still report: 'VariableDeclarator ASTNodes are not handled by markPropTypesAsUsed'

**Comment by golopot** [comment]
This fix is not released yet. The bug will still be present on 7.14.0.

**Comment by yoyo837** [comment]
I thought 7.14.0 has fixed it. Thanks.

**Comment by yannickcr** [comment]
Thanks for the fix @golopot :+1: I just released `v7.14.1` with it.

**Pull request merged**
