### PR TITLE
Added support for nested prop types

### LINKED ISSUE #105: Nested properties and prop-types
Is it an oversight or a limitation that for the `react/prop-types` rule, no warning is emitted for missing nested properties.

For example, with:

```js
propTypes: {
  a: React.PropTypes.shape({
    b: React.PropTypes.shape({
      c: React.PropTypes.func
    })
  })
}
```

I get no warning when I use `this.props.a.b.d`. 

Thank you!

### PR DESCRIPTION
**Pull request by Cellule**
Closes #105 
Support nested prop types and use react propTypes to make further analysis.
Minimal analyse of primitive propTypes.

It uses `React.PropTypes.xxxx` to determine the depth of the property.

I might have missed some edge cases, I tried to cover as much as I could think.

### CODE REVIEW

**Comment by mathieumg** [comment]
:tada: Thank you! :D

**Comment by AlexKVal** [comment]
Great job ! :+1: 

BTW this PR on `react-bootstrap` passes OK :wink:

**Comment by yannickcr** [comment]
Great! I'll check this this evening :smiley:

**Comment by yannickcr** [comment]
Awesome work! Thank you! :tada:

**Pull request merged**
