### PR TITLE
Switch to new eslint rule format (Fixes #661)

### LINKED ISSUE #661: Support ESLint 3 and new rule format
The new rule format, introduced in the ESLint version 3, is explained here http://eslint.org/blog/2016/07/eslint-new-rule-format

Any chance of converting the rules in that format and making a new major release which support ESLint 3 and up?

### PR DESCRIPTION
**Pull request by petersendidit**
The provided [automatic transformation](http://eslint.org/blog/2016/07/eslint-new-rule-format#automatic-transformation) from eslint worked great. 

Merging this will most likely result in conflicts in all open pull requests.

### CODE REVIEW

**Comment by ljharb** [comment]
Awesome! Presumably all the authors of open PRs can run the same transformation and the resulting diffs should be just as useful?

**Comment by petersendidit** [comment]
Should be, might be a little weird since their branch will be trying to do the same changes as this one. Though its possible that running the tool and then doing a rebase might clean things up for them.

**Comment by ljharb** [comment]
Yes, definitely they'd want to do a rebase. Always be rebasing!

**Comment by yannickcr** [comment]
Merged, thanks!

**Pull request merged**
