### PR TITLE
Now only reporting up to once per file for `jsx-filename-extension`

### PR DESCRIPTION
**Pull request by mathieumg**
Things could get very spammy for no reason if you had a lot of JSX in a "disallowed file". I kept the first node for the report since it facilitates locating the culprit.

Let me know if there is anything!

### CODE REVIEW

**Comment by lencioni** [comment]
LGTM

**Comment by yannickcr** [comment]
LGTM too

Can you rebase your branch? Then I'll merge it.

**Comment by mathieumg** [comment]
Done!

**Comment by yannickcr** [comment]
Merged, thanks!

**Pull request merged**
