### PR TITLE
Grammar fix

### PR DESCRIPTION
**Pull request by coryhouse**

### CODE REVIEW

**Comment by ljharb** [comment]
Would you please merge #566, #568, #569, #570, all into the same PR? There's no need to even have these be separate commits.

**Comment by coryhouse** [comment]
These were all performed via a mobile device on github.com so there was no easy way to merge.

**Comment by coryhouse** [comment]
So to answer your question, no, I won't go through the re-work of merging these into one PR.

**Comment by ljharb** [comment]
@coryhouse for future reference, even in that scenario you can continue editing files, in your fork, on the same branch, and it will add commits to the existing PR.

I'll manually squash these.

**Comment by coryhouse** [comment]
Nice! News to me. Thanks for the tip.

**Pull request closed without merging**
