### PR TITLE
Add no-duplicate-props to the recommended rule set

### PR DESCRIPTION
**Pull request by Wilfred**
I'd like to propose adding no-duplicate-props to the recommended rules. I don't see any use case for allow duplicate props, so it seems worthwhile to me.

### CODE REVIEW

**Comment by Wilfred** [comment]
Oops, misread the code. Please ignore.

**Comment by ljharb** [comment]
I actually agree that this rule should be part of the recommended set. This rule catches bugs often.

**Comment by lencioni** [comment]
It is: https://github.com/yannickcr/eslint-plugin-react/blob/fd06c063b32f433f93a4d1fad11575deb6a69d1d/index.js#L94

**Comment by ljharb** [comment]
ah, understood :-)

**Pull request closed without merging**
