### PR TITLE
Resurrection of #2713: add componentWrapperFunctions setting

### PR DESCRIPTION
**Pull request by LandonSchropp**
This PR is my attempt to resurrect the #2713 PR by @jzabala. I haven't changed anything in the original PR other than making the changes suggested by @ljharb and rebasing on top of the latest master.

Please let me know if there's anything else required. I'd really love to land this PR so I can use it. Thanks!

CC @jzabala, @flut1, @ljharb, @jillesme

### CODE REVIEW

**Comment by LandonSchropp** [comment]
@ljharb Bump.

**Comment by LandonSchropp** [comment]
@ljharb Bump again...

**Comment by ljharb** [comment]
@LandonSchropp for future reference, please do not create a redundant PR - instead, comment a link to your branch/commits on the original PR, and i'll update it with those. Now I have to keep both PRs open and in sync until both land, otherwise there'll be an orphan PR ref for eternity.

I'll take a look today.

**Comment by ljharb** [comment]
@LandonSchropp i'm unable to force push to your fork, despite the "allow edits" checkbox being checked - looks like this is because you forked not from this repo, but from jzabala's fork.

I'll force push to #2713, and if you can force push the *same exact sha* to this PR's branch, then i can land both.

**Comment by LandonSchropp** [comment]
@ljharb Okay, I've updated the commit to 495a4cf8. Thanks for tackling this, and let me know if there's anything else I can do.

**Pull request merged**
