### PR TITLE
Fix JSX Syntax

### PR DESCRIPTION
**Pull request by peter-mouland**

### CODE REVIEW

**Comment by brokentone** [comment]
This looks like an improvement to me!

**Comment by ljharb** [comment]
Why did you close #1866 and open this, instead of updating that PR?

**Comment by peter-mouland** [comment]
There are 2 mistakes in the original PR!
Thanks for merging

**Comment by ljharb** [comment]
@peter-mouland in the future, please update the original PR instead of replacing it. I’ll be happy to walk you through it if you have trouble.

**Pull request merged**
