### PR TITLE
[Fix] version detection: support recursive processor virtual filename

### PR DESCRIPTION
**Pull request by JounQin**
continue to work on #2949

---

According to https://github.com/eslint/eslint/pull/14227#discussion_r602802758, virtual filename could be recursive, this PR fix this possible issue.

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
if we're sure there's no chance of an infinite loop here, lgtm

**Comment by JounQin** [comment]
> if we're sure there's no chance of an infinite loop here, lgtm

Sure, that error indicates the filename is a virtual filename and what means a true filename must exist.

**Comment by JounQin** [comment]
@ljharb Any luck to merge?

**Comment by JounQin** [comment]
@ljharb Any luck to merge?

**Pull request merged**
