### PR TITLE
Teach sort-comp rule about static class methods

### LINKED ISSUE #128: sort-comp: statics out of lifecycle?
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md

I think it would make sense to put the statics out of the lifecycle and put them in the order structure. Usually, you put the static variables at the top of your class, then your constructor and then the lifecycle functions.

### PR DESCRIPTION
**Pull request by lencioni**
A number of people have said that they think it makes sense for static
class methods to appear at the very top of classes. This PR allows
this to be configured by adding the `static-methods` keyword to the
sort-comp rule.

While I was at it, I fixed a couple of typos and made a minor perf tweak.

Fixes #128

### CODE REVIEW

**Comment by ljharb** [comment]
Awesome! :+1:

**Comment by adrienbrault** [comment]
Can this include static properties too ?

**Comment by ljharb** [comment]
Those don't exist yet. However, it should once they do :-)

**Comment by yannickcr** [comment]
Thank you very much for this. But since it can be a breaking change in some configuration I will wait for the next major release to merge it.

**Comment by lencioni** [comment]
Sounds good. Is there anything I can do to help get the next major release out sooner?

**Comment by yannickcr** [comment]
Sure. I will publish a checklist (maybe tomorrow) of what I would like to pass in next major release.

**Comment by yannickcr** [comment]
Merged, thanks!

**Pull request merged**
